{% set version = "0.5.0" %}

package:
  name: pylinalg
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/pylinalg/pylinalg-{{ version }}.tar.gz
  sha256: 477b4a2db24c05c950df3285fcfcef9d8d5d8f969e8d2bd9345d5fd001f088a2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - poetry >=1.4.2
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.20.0

test:
  imports:
    - pylinalg
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/pygfx/pygfx
  summary: Linear algebra utilities for Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hmaarrfk
