{% set version = "0.6.7" %}

package:
  name: pylinalg
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/pylinalg/pylinalg-{{ version }}.tar.gz
  sha256: c3f0d01d936129ec4b9cfcdd2cc4f68382a7a3ede0a5a9448091279e1187f204

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - flit-core
  run:
    - python >={{ python_min }}
    - numpy >=1.20.0

test:
  imports:
    - pylinalg
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/pygfx/pylinalg
  summary: Linear algebra utilities for Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hmaarrfk
